const data = [
  {
    couponId: '1721460480822702080',
    couponTitle: '鲜肉燕兑换券（无门槛订单类型通用）',
    couponCode: 'S00038',
    couponType: 'GOODS',
    useReference:
      '鲜肉燕兑换券（无门槛订单类型通用）\n活动时间:领券当日起2天内可用',
    publishQuantity: 100,
    gainQuantity: 8,
    notGainQuantity: 92,
    usedQuantity: 0,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 2,
      validHours: null,
    },
  },
  {
    couponId: '1717832182817320960',
    couponTitle: '测试小数券',
    couponCode: 'M00438',
    couponType: 'REDUCE',
    useReference:
      '测试小数券\n活动时间:领券当日起100天内可用\n优惠内容:全部商品可用，满任意金额可用，减免2.87元优惠券',
    publishQuantity: 100,
    gainQuantity: 24,
    notGainQuantity: 76,
    usedQuantity: 14,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 100,
      validHours: null,
    },
  },
  {
    couponId: '1717075282475577344',
    couponTitle: '嫩豆腐兑换券（有包装费）',
    couponCode: 'S00037',
    couponType: 'GOODS',
    useReference: '嫩豆腐兑换券（有包装费）\n活动时间:领券当日起2天内可用',
    publishQuantity: 50,
    gainQuantity: 8,
    notGainQuantity: 42,
    usedQuantity: 2,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 2,
      validHours: null,
    },
  },
  {
    couponId: '1716374325240291328',
    couponTitle: '无门槛5元（电商可用）',
    couponCode: 'M00437',
    couponType: 'REDUCE',
    useReference:
      '无门槛5元（电商可用）\n活动时间:领券当日起10天内可用\n优惠内容:全部商品可用，满任意金额可用，减免5.00元优惠券',
    publishQuantity: 20,
    gainQuantity: 7,
    notGainQuantity: 6,
    usedQuantity: 7,
    invalidQuantity: 7,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 10,
      validHours: null,
    },
  },
  {
    couponId: '1714466617297264640',
    couponTitle: '满20减3券（支持赠送）',
    couponCode: 'M00436',
    couponType: 'REDUCE',
    useReference:
      '满20减3券（支持赠送）\n优惠内容:全部商品可用，满 20.00 元可用，减免3.00元优惠券',
    publishQuantity: 10,
    gainQuantity: 1,
    notGainQuantity: 9,
    usedQuantity: 1,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'HOURS',
      validBeginTime: null,
      validEndTime: null,
      validDays: null,
      validHours: 24,
    },
  },
  {
    couponId: '1713740668763168768',
    couponTitle: '[全国电商券]支付有礼赠送6折扣券',
    couponCode: 'Z00010',
    couponType: 'PERCENT',
    useReference: '[全国电商券]支付有礼赠送6折扣券',
    publishQuantity: 101,
    gainQuantity: 1,
    notGainQuantity: 100,
    usedQuantity: 0,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'HOURS',
      validBeginTime: null,
      validEndTime: null,
      validDays: null,
      validHours: 8,
    },
  },
  {
    couponId: '1713738969155690496',
    couponTitle: '[全国电商]支付有礼赠送优惠券',
    couponCode: 'M00435',
    couponType: 'REDUCE',
    useReference:
      '[全国电商]支付有礼赠送优惠券\n活动时间:领券当日起3天内可用\n优惠内容:部分商品可用，满 12.00 元可用，减免6.66元优惠券',
    publishQuantity: 1,
    gainQuantity: 1,
    notGainQuantity: 0,
    usedQuantity: 1,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 3,
      validHours: null,
    },
  },
  {
    couponId: '1712404406408110080',
    couponTitle: '【权益赠券】权益到期是否赠送验证',
    couponCode: 'S00036',
    couponType: 'GOODS',
    useReference:
      '【权益赠券】权益到期是否赠送验证\n活动时间:领券当日起3天内可用',
    publishQuantity: 50,
    gainQuantity: 3,
    notGainQuantity: 47,
    usedQuantity: 0,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 3,
      validHours: null,
    },
  },
  {
    couponId: '1712399231782019072',
    couponTitle: '6元满减券领券8小时内有效',
    couponCode: 'M00434',
    couponType: 'REDUCE',
    useReference:
      '6元满减券领券8小时内有效\n优惠内容:全部商品可用，满任意金额可用，减免6.00元优惠券',
    publishQuantity: 60,
    gainQuantity: 25,
    notGainQuantity: 35,
    usedQuantity: 8,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'HOURS',
      validBeginTime: null,
      validEndTime: null,
      validDays: null,
      validHours: 8,
    },
  },
  {
    couponId: '1712313754861232128',
    couponTitle: '【开卡礼包】满20减3元券',
    couponCode: 'M00433',
    couponType: 'REDUCE',
    useReference:
      '【开卡礼包】满20减3元券\n活动时间:领券当日起2天内可用\n优惠内容:部分商品可用，满任意金额可用，减免3.00元优惠券',
    publishQuantity: 10,
    gainQuantity: 3,
    notGainQuantity: 7,
    usedQuantity: 0,
    invalidQuantity: 0,
    useFlag: true,
    couponGetRuleInfo: {
      validType: 'DAYS',
      validBeginTime: null,
      validEndTime: null,
      validDays: 2,
      validHours: null,
    },
  },
];

export default data;
